# Generated by Django 5.0.3 on 2024-03-31 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_summarie_user_alter_conectsubjectwithsummarie_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarie',
            name='user',
        ),
        migrations.AlterField(
            model_name='conectsubjectwithsummarie',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
